version: '3.8'

services:
  selenium:
    image: selenium/standalone-chrome:latest
    container_name: selenium
    ports:
      - "4444:4444"
      - "5900:5900"
      - "7900:7900"
    environment:
      # - SE_VNC_PASSWORD=secret
      - SE_VNC_NO_PASSWORD=1
      - SE_START_VNC=true
  
  bot-scraper:
    build: ./bot-scraper
    container_name: bot-scraper
    depends_on:
      - selenium
    environment:
      - GET_MSG=http://api-telegram/msg
      - TIME_REFRESH_SECONDS=60
      - SELENIUM_SERVER=http://selenium:4444/wd/hub
      - ENV=prod # prod, dev
    
  bot-telegram:
    build: ./bot-telegram
    container_name: bot-telegram
    environment:
      - TOKEN=${TELEGRAM_TOKEN}
    volumes:
      - ./db:/users

  api-telegram:
    build: ./api-telegram
    container_name: api-telegram
    environment:
      - TOKEN=${TELEGRAM_TOKEN}
    volumes:
      - ./db:/users
  

